# Visual Cue Evaluation Pipeline Configuration

# Dataset Configuration
dataset:
  cityscapes_root: "/scratch/kesuniot_root/kesuniot0/jackyjin/GeoEvalPipeline"
  images_per_city: 2
  cities: ["aachen", "bochum"]  # Available cities in train set 
  selection_method: "systematic"  # "systematic", "first_n", "evenly_spaced"
  
# Visual Features Configuration  
features:
  target_features: ["vehicle", "construction"]
  target_labels: null  # Optional: specific label names instead of categories (e.g., ["person", "rider"])
  combine_masks: false  # Create separate masks for each feature vs combined
  mask_suffix: "mask"
  dilate_masks: true  # Apply dilation to masks for better CLIPAway performance
  kernel_size: 5  # Dilation kernel size
  dilation_iterations: 5  # Number of dilation iterations
  
# Image Processing Configuration
processing:
  image_size: 512  # Target size for split images
  batch_size: 5
  
# CLIPAway Configuration
clipaway:
  path: "/scratch/kesuniot_root/kesuniot0/jackyjin/GeoEvalPipeline/CLIPAway"
  device: "cuda"  # "cuda" or "cpu"
  strength: 1
  scale: 1
  seed: 42
  display_focused_embeds: false
  model_key: "botp/stable-diffusion-v1-5-inpainting"
  
# Evaluation Configuration
evaluation:
  model: "gpt-4o"
  concurrent_requests: 3
  cache_responses: true
  use_ground_truth: true
  max_images: null  # null = process all selected images
  
# Output Configuration
output:
  base_directory: "pipeline/output"
  structure:
    masks: "masks"
    processed: "processed" 
    clipaway: "clipaway_results"
    evaluation: "evaluation_results"
  cleanup_intermediate: false
  save_debug_info: true
  
# Logging Configuration
logging:
  level: "ERROR"  # "DEBUG", "INFO", "WARNING", "ERROR"
  file: "pipeline/logs/pipeline.log"
  console: true
  
# Performance Configuration
performance:
  max_workers: 4
  memory_limit_gb: 16
  gpu_memory_fraction: 0.8
  
